# Labels: define labels for Issues and Pull Requests
labels:
  - name: ğŸ§® backend
    color: #E59F53
    
  - name: ğŸˆ frontend
    color: #CAF5CD
    
  - name: ğŸ“˜ documentation
    color: #0075ca
    
  - name: ğŸ“ˆ enhancement
    color: #a2eeef
    
  - name: ğŸŒ± good first issue
    color: #7057ff
    
  - name: ğŸ›Ÿ help wanted
    color: #008672
    
  - name: âŒ invalid
    color: #e4e669
    
  - name: ğŸ–‹ï¸ orthographe/syntaxe
    color: #A14E01
    
  - name: â“ question
    color: #d876e3
    
  - name: âœ¨ style
    color: #4BE836
